# Generated by Django 4.0.6 on 2022-07-15 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('body', models.CharField(max_length=50000)),
            ],
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
